/* eslint-disable */
// Pull in the React Three Fiber JSX bridge from the frontend package so the
// worker's tsc (which resolves @/* → ../frontend/src/*) recognises Three.js
// JSX elements (mesh, group, etc.) in council-scene.tsx.
/// <reference path="../frontend/src/r3f.d.ts" />
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces:
      | "Chat"
      | "OrchestratorAgent"
      | "RecruiterAgent"
      | "TechnicalInterviewerAgent"
      | "CultureInterviewerAgent"
      | "DomainExpertAgent"
      | "BehavioralInterviewerAgent"
      | "BiasAuditAgent"
      | "SharedMemoryDO";
  }
  interface Env {
    AI_PROVIDER?: "workers-ai" | "openai-compatible" | "groq";
    AI_MODEL?: string;
    AI_BASE_URL?: string;
    AI_API_KEY?: string;
    GREENHOUSE_API_KEY: string;
    Chat: DurableObjectNamespace<import("@panelai/agents").Chat>;
    ORCHESTRATOR: DurableObjectNamespace<
      import("@panelai/agents").OrchestratorAgent
    >;
    RECRUITER: DurableObjectNamespace<import("@panelai/agents").RecruiterAgent>;
    TECHNICAL_INTERVIEWER: DurableObjectNamespace<
      import("@panelai/agents").TechnicalInterviewerAgent
    >;
    CULTURE_INTERVIEWER: DurableObjectNamespace<
      import("@panelai/agents").CultureInterviewerAgent
    >;
    DOMAIN_EXPERT: DurableObjectNamespace<
      import("@panelai/agents").DomainExpertAgent
    >;
    BEHAVIORAL_INTERVIEWER: DurableObjectNamespace<
      import("@panelai/agents").BehavioralInterviewerAgent
    >;
    BIAS_AUDIT: DurableObjectNamespace<
      import("@panelai/agents").BiasAuditAgent
    >;
    SharedMemory: DurableObjectNamespace<
      import("@panelai/core").SharedMemoryDO
    >;
    AI: Ai;
  }
}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "GREENHOUSE_API_KEY"
      | "AI_PROVIDER"
      | "AI_MODEL"
      | "AI_BASE_URL"
      | "AI_API_KEY"
    >
  > {}
}
