/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "Chat";
	}
	interface Env {
		OPENAI_API_KEY: string;
		Chat: DurableObjectNamespace<import("@panelai/agents").Chat>;
		AI: Ai;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY">> {}
}
